Update create_graph.py
mimosa-project/emgraph pull request #2
Opened 2019-09-25 04:24 UTC by azsgws

Implementation of the hierarchical

2019-09-25 05:22 UTC, azsgws commented
add result json_file, and add html_file and js_file to view the graph

2019-10-01 06:52 UTC, aabaa requested changes

2019-10-01 06:52 UTC, aabaa commented on demo/create_graph.py
> +    def __init__(self, name, target_nodes, source_nodes, x, y, href, is_dummy):
name以外はデフォルト値をセットできたほうが良いでしょう

2019-10-01 06:52 UTC, aabaa commented on demo/create_graph.py
> +def create_node_list():
引数が抜けています

2019-10-01 06:52 UTC, aabaa commented on demo/create_graph.py
> +        n = Node(k, set(), set(), -1, -1, v[1], False)
Nodeのコンストラクトのデフォルト引数

2019-10-01 06:52 UTC, aabaa commented on demo/create_graph.py
> +    node_dict = {}
keyとvalueの説明を書いてください．
名前はname2nodeのほうが良かったかもしれません．

2019-10-01 06:52 UTC, aabaa commented on demo/create_graph.py
> +        random.shuffle(keys)
シャッフルは一回で十分

2019-10-01 06:52 UTC, aabaa commented on demo/create_graph.py
> +        keys = [(key, d[key]) for key in keys]
型が変わるので，keysではなく違う名前の変数を用意するかダイレクトに
return dict([(key, d[key]) for key in keys])
と書く

2019-10-01 06:52 UTC, aabaa commented on demo/draw_graph.js
> +        var cy = cytoscape({
基本的にvarは使わずletを使ってください

2019-10-02 04:48 UTC, azsgws commented
Fix these change requests.

2019-10-02 06:50 UTC, aabaa requested changes
関数名ではなく，変数 node_dict を変更してください．
node_dict -> name2node
です

2019-10-02 06:50 UTC, aabaa commented on demo/create_graph.py
> +    node_dict = {}
関数名ではなく，変数 node_dict を変更してください．
node_dict -> name2node
です

2019-10-02 07:33 UTC, aabaa approved these changes

2019-10-02 07:33 UTC, merged