階層割り当てを行う関数の修正
mimosa-project/emgraph pull request #61
Opened 2021-01-15 08:12 UTC by azsgws

node_list -> nodes
階層割り当ての操作をassign_nodesを呼ぶだけで完了するように変更

2021-01-15 08:52 UTC, azsgws commented
#62　create_graphのリファクタリング

2021-01-21 07:40 UTC, aabaa requested changes

2021-01-21 07:40 UTC, aabaa commented on demo/create_graph.py
> +def assign_top_node(nodes):
assign_top_node -> collect_top_nodes

2021-01-21 07:40 UTC, aabaa commented on demo/create_graph.py
>              top_node.x = 0
消す

2021-01-21 07:40 UTC, aabaa commented on demo/create_graph.py
> +    for top_node in top_nodes:
前に追加
```python
for node in top_nodes:
    node.x = 0
    node.y = 0
```

2021-01-21 07:40 UTC, aabaa commented on demo/create_graph.py
>          if assign_node.x < 0:
この下に
```python
if any([a.x < 0 for a in target.targets]):
    continue
```
でガードする

2021-01-21 07:40 UTC, aabaa commented on demo/create_graph.py
> +            assign_level2node_recursively(nodes, assign_node, assign_node_level)
不要になるはず．assert Falseして通らないことをチェックする

2021-02-04 06:40 UTC, aabaa requested changes

2021-02-04 06:40 UTC, aabaa commented on demo/create_graph.py
> +    sorted_nodes = remove_duplication(sorted_nodes)
不要なので消す

2021-02-04 06:40 UTC, aabaa commented on demo/create_graph.py
> +    return a_sorted
削除

2021-02-04 06:40 UTC, aabaa commented on demo/create_graph.py
> +        if node.x < 0:
assert node.x < 0
に変更

2021-02-05 01:26 UTC, aabaa requested changes

2021-02-05 01:26 UTC, aabaa commented on demo/create_graph.py
> +                continue
ここでnon_assigned_nodesにappendするほうが良い

2021-02-05 01:26 UTC, aabaa commented on demo/create_graph.py
> +        non_assigned_nodes = [n for n in non_assigned_nodes if n.x < 0]
non_assigned_nodesを線形検索するよりは，assign_level2node()の戻り値としたほうが良いです．

2021-04-26 08:52 UTC, merged